# Generated by Django 5.1.7 on 2025-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default-course.jpg.webp', upload_to='course_images/'),
        ),
    ]
